// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.proto

package schemago

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SkillInfo_SkillType int32

const (
	SkillInfo_Unknown SkillInfo_SkillType = 0
	SkillInfo_System  SkillInfo_SkillType = 1
	SkillInfo_User    SkillInfo_SkillType = 2
)

var SkillInfo_SkillType_name = map[int32]string{
	0: "Unknown",
	1: "System",
	2: "User",
}

var SkillInfo_SkillType_value = map[string]int32{
	"Unknown": 0,
	"System":  1,
	"User":    2,
}

func (x SkillInfo_SkillType) String() string {
	return proto.EnumName(SkillInfo_SkillType_name, int32(x))
}

func (SkillInfo_SkillType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0, 0}
}

type SkillAnswer_AnswerType int32

const (
	SkillAnswer_Unknown SkillAnswer_AnswerType = 0
	SkillAnswer_Text    SkillAnswer_AnswerType = 1
	SkillAnswer_Audio   SkillAnswer_AnswerType = 2
	SkillAnswer_Complex SkillAnswer_AnswerType = 3
)

var SkillAnswer_AnswerType_name = map[int32]string{
	0: "Unknown",
	1: "Text",
	2: "Audio",
	3: "Complex",
}

var SkillAnswer_AnswerType_value = map[string]int32{
	"Unknown": 0,
	"Text":    1,
	"Audio":   2,
	"Complex": 3,
}

func (x SkillAnswer_AnswerType) String() string {
	return proto.EnumName(SkillAnswer_AnswerType_name, int32(x))
}

func (SkillAnswer_AnswerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1, 0}
}

type TextInfo_FullAnswer_TextAnswerType int32

const (
	TextInfo_FullAnswer_Unknown   TextInfo_FullAnswer_TextAnswerType = 0
	TextInfo_FullAnswer_Markdown  TextInfo_FullAnswer_TextAnswerType = 1
	TextInfo_FullAnswer_PlainText TextInfo_FullAnswer_TextAnswerType = 2
)

var TextInfo_FullAnswer_TextAnswerType_name = map[int32]string{
	0: "Unknown",
	1: "Markdown",
	2: "PlainText",
}

var TextInfo_FullAnswer_TextAnswerType_value = map[string]int32{
	"Unknown":   0,
	"Markdown":  1,
	"PlainText": 2,
}

func (x TextInfo_FullAnswer_TextAnswerType) String() string {
	return proto.EnumName(TextInfo_FullAnswer_TextAnswerType_name, int32(x))
}

func (TextInfo_FullAnswer_TextAnswerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2, 0, 0}
}

type AudioResource_AudioType int32

const (
	AudioResource_Unknown AudioResource_AudioType = 0
	AudioResource_Music   AudioResource_AudioType = 1
	AudioResource_TTS     AudioResource_AudioType = 2
)

var AudioResource_AudioType_name = map[int32]string{
	0: "Unknown",
	1: "Music",
	2: "TTS",
}

var AudioResource_AudioType_value = map[string]int32{
	"Unknown": 0,
	"Music":   1,
	"TTS":     2,
}

func (x AudioResource_AudioType) String() string {
	return proto.EnumName(AudioResource_AudioType_name, int32(x))
}

func (AudioResource_AudioType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5, 0}
}

type ComplexInfo_ViewType int32

const (
	ComplexInfo_Unknown  ComplexInfo_ViewType = 0
	ComplexInfo_Card     ComplexInfo_ViewType = 1
	ComplexInfo_Playlist ComplexInfo_ViewType = 2
	ComplexInfo_Table    ComplexInfo_ViewType = 3
	ComplexInfo_Carousel ComplexInfo_ViewType = 4
)

var ComplexInfo_ViewType_name = map[int32]string{
	0: "Unknown",
	1: "Card",
	2: "Playlist",
	3: "Table",
	4: "Carousel",
}

var ComplexInfo_ViewType_value = map[string]int32{
	"Unknown":  0,
	"Card":     1,
	"Playlist": 2,
	"Table":    3,
	"Carousel": 4,
}

func (x ComplexInfo_ViewType) String() string {
	return proto.EnumName(ComplexInfo_ViewType_name, int32(x))
}

func (ComplexInfo_ViewType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 0}
}

type ComplexInfo_CardInfo_Layout int32

const (
	ComplexInfo_CardInfo_Unknown ComplexInfo_CardInfo_Layout = 0
	ComplexInfo_CardInfo_Top     ComplexInfo_CardInfo_Layout = 1
	ComplexInfo_CardInfo_Left    ComplexInfo_CardInfo_Layout = 2
	ComplexInfo_CardInfo_Right   ComplexInfo_CardInfo_Layout = 3
	ComplexInfo_CardInfo_Bottom  ComplexInfo_CardInfo_Layout = 4
)

var ComplexInfo_CardInfo_Layout_name = map[int32]string{
	0: "Unknown",
	1: "Top",
	2: "Left",
	3: "Right",
	4: "Bottom",
}

var ComplexInfo_CardInfo_Layout_value = map[string]int32{
	"Unknown": 0,
	"Top":     1,
	"Left":    2,
	"Right":   3,
	"Bottom":  4,
}

func (x ComplexInfo_CardInfo_Layout) String() string {
	return proto.EnumName(ComplexInfo_CardInfo_Layout_name, int32(x))
}

func (ComplexInfo_CardInfo_Layout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 0, 0}
}

type ComplexInfo_TableInfo_TableCell_TableCellType int32

const (
	ComplexInfo_TableInfo_TableCell_Unknown ComplexInfo_TableInfo_TableCell_TableCellType = 0
	ComplexInfo_TableInfo_TableCell_Text    ComplexInfo_TableInfo_TableCell_TableCellType = 1
	ComplexInfo_TableInfo_TableCell_Image   ComplexInfo_TableInfo_TableCell_TableCellType = 2
)

var ComplexInfo_TableInfo_TableCell_TableCellType_name = map[int32]string{
	0: "Unknown",
	1: "Text",
	2: "Image",
}

var ComplexInfo_TableInfo_TableCell_TableCellType_value = map[string]int32{
	"Unknown": 0,
	"Text":    1,
	"Image":   2,
}

func (x ComplexInfo_TableInfo_TableCell_TableCellType) String() string {
	return proto.EnumName(ComplexInfo_TableInfo_TableCell_TableCellType_name, int32(x))
}

func (ComplexInfo_TableInfo_TableCell_TableCellType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 2, 0, 0}
}

type ControlInfo_ControlCategory int32

const (
	ControlInfo_Unknown       ControlInfo_ControlCategory = 0
	ControlInfo_AppControl    ControlInfo_ControlCategory = 1
	ControlInfo_PlayControl   ControlInfo_ControlCategory = 2
	ControlInfo_DeviceControl ControlInfo_ControlCategory = 3
	ControlInfo_PageControl   ControlInfo_ControlCategory = 4
)

var ControlInfo_ControlCategory_name = map[int32]string{
	0: "Unknown",
	1: "AppControl",
	2: "PlayControl",
	3: "DeviceControl",
	4: "PageControl",
}

var ControlInfo_ControlCategory_value = map[string]int32{
	"Unknown":       0,
	"AppControl":    1,
	"PlayControl":   2,
	"DeviceControl": 3,
	"PageControl":   4,
}

func (x ControlInfo_ControlCategory) String() string {
	return proto.EnumName(ControlInfo_ControlCategory_name, int32(x))
}

func (ControlInfo_ControlCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9, 0}
}

type ControlInfo_AppCommand int32

const (
	ControlInfo_Open  ControlInfo_AppCommand = 0
	ControlInfo_Close ControlInfo_AppCommand = 1
)

var ControlInfo_AppCommand_name = map[int32]string{
	0: "Open",
	1: "Close",
}

var ControlInfo_AppCommand_value = map[string]int32{
	"Open":  0,
	"Close": 1,
}

func (x ControlInfo_AppCommand) String() string {
	return proto.EnumName(ControlInfo_AppCommand_name, int32(x))
}

func (ControlInfo_AppCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9, 1}
}

type ControlInfo_PlayCommand int32

const (
	ControlInfo_Prev                ControlInfo_PlayCommand = 0
	ControlInfo_Next                ControlInfo_PlayCommand = 1
	ControlInfo_Favorite            ControlInfo_PlayCommand = 2
	ControlInfo_UnFavorite          ControlInfo_PlayCommand = 3
	ControlInfo_PlayModelDefault    ControlInfo_PlayCommand = 4
	ControlInfo_PlayModelLoop       ControlInfo_PlayCommand = 5
	ControlInfo_PlayModelRandom     ControlInfo_PlayCommand = 6
	ControlInfo_PlayModelRandomLoop ControlInfo_PlayCommand = 7
	ControlInfo_PlayModelSingleLoop ControlInfo_PlayCommand = 8
	ControlInfo_SeekTo              ControlInfo_PlayCommand = 9
	ControlInfo_FastForward         ControlInfo_PlayCommand = 10
	ControlInfo_Rewind              ControlInfo_PlayCommand = 11
	ControlInfo_FastForwardTo       ControlInfo_PlayCommand = 12
	ControlInfo_RewindTo            ControlInfo_PlayCommand = 13
	ControlInfo_Replay              ControlInfo_PlayCommand = 14
	ControlInfo_Play                ControlInfo_PlayCommand = 15
	ControlInfo_Stop                ControlInfo_PlayCommand = 16
	ControlInfo_Resume              ControlInfo_PlayCommand = 17
	ControlInfo_Pause               ControlInfo_PlayCommand = 18
	ControlInfo_Speed               ControlInfo_PlayCommand = 19
	ControlInfo_Quality             ControlInfo_PlayCommand = 20
)

var ControlInfo_PlayCommand_name = map[int32]string{
	0:  "Prev",
	1:  "Next",
	2:  "Favorite",
	3:  "UnFavorite",
	4:  "PlayModelDefault",
	5:  "PlayModelLoop",
	6:  "PlayModelRandom",
	7:  "PlayModelRandomLoop",
	8:  "PlayModelSingleLoop",
	9:  "SeekTo",
	10: "FastForward",
	11: "Rewind",
	12: "FastForwardTo",
	13: "RewindTo",
	14: "Replay",
	15: "Play",
	16: "Stop",
	17: "Resume",
	18: "Pause",
	19: "Speed",
	20: "Quality",
}

var ControlInfo_PlayCommand_value = map[string]int32{
	"Prev":                0,
	"Next":                1,
	"Favorite":            2,
	"UnFavorite":          3,
	"PlayModelDefault":    4,
	"PlayModelLoop":       5,
	"PlayModelRandom":     6,
	"PlayModelRandomLoop": 7,
	"PlayModelSingleLoop": 8,
	"SeekTo":              9,
	"FastForward":         10,
	"Rewind":              11,
	"FastForwardTo":       12,
	"RewindTo":            13,
	"Replay":              14,
	"Play":                15,
	"Stop":                16,
	"Resume":              17,
	"Pause":               18,
	"Speed":               19,
	"Quality":             20,
}

func (x ControlInfo_PlayCommand) String() string {
	return proto.EnumName(ControlInfo_PlayCommand_name, int32(x))
}

func (ControlInfo_PlayCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9, 2}
}

type ControlInfo_DeviceCommand int32

const (
	ControlInfo_Boot           ControlInfo_DeviceCommand = 0
	ControlInfo_Reboot         ControlInfo_DeviceCommand = 1
	ControlInfo_Shutdown       ControlInfo_DeviceCommand = 2
	ControlInfo_BrightnessUp   ControlInfo_DeviceCommand = 3
	ControlInfo_BrightnessDown ControlInfo_DeviceCommand = 4
	ControlInfo_BrightnessTo   ControlInfo_DeviceCommand = 5
	ControlInfo_EnterBle       ControlInfo_DeviceCommand = 6
	ControlInfo_ExitBle        ControlInfo_DeviceCommand = 7
	ControlInfo_VolumeUp       ControlInfo_DeviceCommand = 8
	ControlInfo_VolumeDown     ControlInfo_DeviceCommand = 9
	ControlInfo_VolumeTo       ControlInfo_DeviceCommand = 10
	ControlInfo_Mute           ControlInfo_DeviceCommand = 11
	ControlInfo_UnMute         ControlInfo_DeviceCommand = 12
	ControlInfo_MicOpen        ControlInfo_DeviceCommand = 13
	ControlInfo_MicClose       ControlInfo_DeviceCommand = 14
)

var ControlInfo_DeviceCommand_name = map[int32]string{
	0:  "Boot",
	1:  "Reboot",
	2:  "Shutdown",
	3:  "BrightnessUp",
	4:  "BrightnessDown",
	5:  "BrightnessTo",
	6:  "EnterBle",
	7:  "ExitBle",
	8:  "VolumeUp",
	9:  "VolumeDown",
	10: "VolumeTo",
	11: "Mute",
	12: "UnMute",
	13: "MicOpen",
	14: "MicClose",
}

var ControlInfo_DeviceCommand_value = map[string]int32{
	"Boot":           0,
	"Reboot":         1,
	"Shutdown":       2,
	"BrightnessUp":   3,
	"BrightnessDown": 4,
	"BrightnessTo":   5,
	"EnterBle":       6,
	"ExitBle":        7,
	"VolumeUp":       8,
	"VolumeDown":     9,
	"VolumeTo":       10,
	"Mute":           11,
	"UnMute":         12,
	"MicOpen":        13,
	"MicClose":       14,
}

func (x ControlInfo_DeviceCommand) String() string {
	return proto.EnumName(ControlInfo_DeviceCommand_name, int32(x))
}

func (ControlInfo_DeviceCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9, 3}
}

type ControlInfo_PageCommand int32

const (
	ControlInfo_Click     ControlInfo_PageCommand = 0
	ControlInfo_LongClick ControlInfo_PageCommand = 1
	ControlInfo_Refresh   ControlInfo_PageCommand = 2
	ControlInfo_Back      ControlInfo_PageCommand = 3
	ControlInfo_Check     ControlInfo_PageCommand = 4
	ControlInfo_UnCheck   ControlInfo_PageCommand = 5
	ControlInfo_SlideUp   ControlInfo_PageCommand = 6
	ControlInfo_SlideDown ControlInfo_PageCommand = 7
)

var ControlInfo_PageCommand_name = map[int32]string{
	0: "Click",
	1: "LongClick",
	2: "Refresh",
	3: "Back",
	4: "Check",
	5: "UnCheck",
	6: "SlideUp",
	7: "SlideDown",
}

var ControlInfo_PageCommand_value = map[string]int32{
	"Click":     0,
	"LongClick": 1,
	"Refresh":   2,
	"Back":      3,
	"Check":     4,
	"UnCheck":   5,
	"SlideUp":   6,
	"SlideDown": 7,
}

func (x ControlInfo_PageCommand) String() string {
	return proto.EnumName(ControlInfo_PageCommand_name, int32(x))
}

func (ControlInfo_PageCommand) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9, 4}
}

type SkillInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SkillId              string   `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	SkillType            string   `protobuf:"bytes,3,opt,name=skill_type,json=skillType,proto3" json:"skill_type,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Author               string   `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Icon                 string   `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	PubTime              int64    `protobuf:"varint,7,opt,name=pub_time,json=pubTime,proto3" json:"pub_time,omitempty"`
	Version              string   `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkillInfo) Reset()         { *m = SkillInfo{} }
func (m *SkillInfo) String() string { return proto.CompactTextString(m) }
func (*SkillInfo) ProtoMessage()    {}
func (*SkillInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}
func (m *SkillInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillInfo.Unmarshal(m, b)
}
func (m *SkillInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillInfo.Marshal(b, m, deterministic)
}
func (m *SkillInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillInfo.Merge(m, src)
}
func (m *SkillInfo) XXX_Size() int {
	return xxx_messageInfo_SkillInfo.Size(m)
}
func (m *SkillInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SkillInfo proto.InternalMessageInfo

func (m *SkillInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SkillInfo) GetSkillId() string {
	if m != nil {
		return m.SkillId
	}
	return ""
}

func (m *SkillInfo) GetSkillType() string {
	if m != nil {
		return m.SkillType
	}
	return ""
}

func (m *SkillInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *SkillInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *SkillInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *SkillInfo) GetPubTime() int64 {
	if m != nil {
		return m.PubTime
	}
	return 0
}

func (m *SkillInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SkillAnswer struct {
	Complete             bool         `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	AnswerType           string       `protobuf:"bytes,2,opt,name=answer_type,json=answerType,proto3" json:"answer_type,omitempty"`
	TextInfo             *TextInfo    `protobuf:"bytes,3,opt,name=text_info,json=textInfo,proto3" json:"text_info,omitempty"`
	AudioInfo            *AudioInfo   `protobuf:"bytes,4,opt,name=audio_info,json=audioInfo,proto3" json:"audio_info,omitempty"`
	ComplexInfo          *ComplexInfo `protobuf:"bytes,5,opt,name=complex_info,json=complexInfo,proto3" json:"complex_info,omitempty"`
	Control              *ControlInfo `protobuf:"bytes,6,opt,name=control,proto3" json:"control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SkillAnswer) Reset()         { *m = SkillAnswer{} }
func (m *SkillAnswer) String() string { return proto.CompactTextString(m) }
func (*SkillAnswer) ProtoMessage()    {}
func (*SkillAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}
func (m *SkillAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkillAnswer.Unmarshal(m, b)
}
func (m *SkillAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkillAnswer.Marshal(b, m, deterministic)
}
func (m *SkillAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkillAnswer.Merge(m, src)
}
func (m *SkillAnswer) XXX_Size() int {
	return xxx_messageInfo_SkillAnswer.Size(m)
}
func (m *SkillAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_SkillAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_SkillAnswer proto.InternalMessageInfo

func (m *SkillAnswer) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *SkillAnswer) GetAnswerType() string {
	if m != nil {
		return m.AnswerType
	}
	return ""
}

func (m *SkillAnswer) GetTextInfo() *TextInfo {
	if m != nil {
		return m.TextInfo
	}
	return nil
}

func (m *SkillAnswer) GetAudioInfo() *AudioInfo {
	if m != nil {
		return m.AudioInfo
	}
	return nil
}

func (m *SkillAnswer) GetComplexInfo() *ComplexInfo {
	if m != nil {
		return m.ComplexInfo
	}
	return nil
}

func (m *SkillAnswer) GetControl() *ControlInfo {
	if m != nil {
		return m.Control
	}
	return nil
}

type TextInfo struct {
	ShortAnswer          string               `protobuf:"bytes,1,opt,name=short_answer,json=shortAnswer,proto3" json:"short_answer,omitempty"`
	FullAnswer           *TextInfo_FullAnswer `protobuf:"bytes,2,opt,name=full_answer,json=fullAnswer,proto3" json:"full_answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TextInfo) Reset()         { *m = TextInfo{} }
func (m *TextInfo) String() string { return proto.CompactTextString(m) }
func (*TextInfo) ProtoMessage()    {}
func (*TextInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}
func (m *TextInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextInfo.Unmarshal(m, b)
}
func (m *TextInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextInfo.Marshal(b, m, deterministic)
}
func (m *TextInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextInfo.Merge(m, src)
}
func (m *TextInfo) XXX_Size() int {
	return xxx_messageInfo_TextInfo.Size(m)
}
func (m *TextInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TextInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TextInfo proto.InternalMessageInfo

func (m *TextInfo) GetShortAnswer() string {
	if m != nil {
		return m.ShortAnswer
	}
	return ""
}

func (m *TextInfo) GetFullAnswer() *TextInfo_FullAnswer {
	if m != nil {
		return m.FullAnswer
	}
	return nil
}

type TextInfo_FullAnswer struct {
	AnswerType           string   `protobuf:"bytes,1,opt,name=answer_type,json=answerType,proto3" json:"answer_type,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TextInfo_FullAnswer) Reset()         { *m = TextInfo_FullAnswer{} }
func (m *TextInfo_FullAnswer) String() string { return proto.CompactTextString(m) }
func (*TextInfo_FullAnswer) ProtoMessage()    {}
func (*TextInfo_FullAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2, 0}
}
func (m *TextInfo_FullAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextInfo_FullAnswer.Unmarshal(m, b)
}
func (m *TextInfo_FullAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextInfo_FullAnswer.Marshal(b, m, deterministic)
}
func (m *TextInfo_FullAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextInfo_FullAnswer.Merge(m, src)
}
func (m *TextInfo_FullAnswer) XXX_Size() int {
	return xxx_messageInfo_TextInfo_FullAnswer.Size(m)
}
func (m *TextInfo_FullAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_TextInfo_FullAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_TextInfo_FullAnswer proto.InternalMessageInfo

func (m *TextInfo_FullAnswer) GetAnswerType() string {
	if m != nil {
		return m.AnswerType
	}
	return ""
}

func (m *TextInfo_FullAnswer) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type Author struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Names                string   `protobuf:"bytes,2,opt,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}
func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (m *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(m, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Author) GetNames() string {
	if m != nil {
		return m.Names
	}
	return ""
}

type Album struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string    `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Authors              []*Author `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	Cover                string    `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Album) Reset()         { *m = Album{} }
func (m *Album) String() string { return proto.CompactTextString(m) }
func (*Album) ProtoMessage()    {}
func (*Album) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}
func (m *Album) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Album.Unmarshal(m, b)
}
func (m *Album) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Album.Marshal(b, m, deterministic)
}
func (m *Album) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Album.Merge(m, src)
}
func (m *Album) XXX_Size() int {
	return xxx_messageInfo_Album.Size(m)
}
func (m *Album) XXX_DiscardUnknown() {
	xxx_messageInfo_Album.DiscardUnknown(m)
}

var xxx_messageInfo_Album proto.InternalMessageInfo

func (m *Album) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Album) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *Album) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *Album) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

type AudioResource struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string    `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Content              string    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AudioType            string    `protobuf:"bytes,4,opt,name=audio_type,json=audioType,proto3" json:"audio_type,omitempty"`
	Authors              []*Author `protobuf:"bytes,5,rep,name=authors,proto3" json:"authors,omitempty"`
	Duration             int64     `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	Cover                string    `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Album                *Album    `protobuf:"bytes,8,opt,name=album,proto3" json:"album,omitempty"`
	Mid                  string    `protobuf:"bytes,9,opt,name=mid,proto3" json:"mid,omitempty"`
	VoiceMode            string    `protobuf:"bytes,10,opt,name=voice_mode,json=voiceMode,proto3" json:"voice_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AudioResource) Reset()         { *m = AudioResource{} }
func (m *AudioResource) String() string { return proto.CompactTextString(m) }
func (*AudioResource) ProtoMessage()    {}
func (*AudioResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}
func (m *AudioResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioResource.Unmarshal(m, b)
}
func (m *AudioResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioResource.Marshal(b, m, deterministic)
}
func (m *AudioResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioResource.Merge(m, src)
}
func (m *AudioResource) XXX_Size() int {
	return xxx_messageInfo_AudioResource.Size(m)
}
func (m *AudioResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioResource.DiscardUnknown(m)
}

var xxx_messageInfo_AudioResource proto.InternalMessageInfo

func (m *AudioResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AudioResource) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AudioResource) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AudioResource) GetAudioType() string {
	if m != nil {
		return m.AudioType
	}
	return ""
}

func (m *AudioResource) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *AudioResource) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *AudioResource) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *AudioResource) GetAlbum() *Album {
	if m != nil {
		return m.Album
	}
	return nil
}

func (m *AudioResource) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *AudioResource) GetVoiceMode() string {
	if m != nil {
		return m.VoiceMode
	}
	return ""
}

type AudioInfo struct {
	TextAnswer           *TextInfo        `protobuf:"bytes,1,opt,name=text_answer,json=textAnswer,proto3" json:"text_answer,omitempty"`
	AudioResourceGroup   []*AudioResource `protobuf:"bytes,2,rep,name=audio_resource_group,json=audioResourceGroup,proto3" json:"audio_resource_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AudioInfo) Reset()         { *m = AudioInfo{} }
func (m *AudioInfo) String() string { return proto.CompactTextString(m) }
func (*AudioInfo) ProtoMessage()    {}
func (*AudioInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}
func (m *AudioInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioInfo.Unmarshal(m, b)
}
func (m *AudioInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioInfo.Marshal(b, m, deterministic)
}
func (m *AudioInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioInfo.Merge(m, src)
}
func (m *AudioInfo) XXX_Size() int {
	return xxx_messageInfo_AudioInfo.Size(m)
}
func (m *AudioInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AudioInfo proto.InternalMessageInfo

func (m *AudioInfo) GetTextAnswer() *TextInfo {
	if m != nil {
		return m.TextAnswer
	}
	return nil
}

func (m *AudioInfo) GetAudioResourceGroup() []*AudioResource {
	if m != nil {
		return m.AudioResourceGroup
	}
	return nil
}

type ImageResource struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Author               string   `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Mid                  string   `protobuf:"bytes,5,opt,name=mid,proto3" json:"mid,omitempty"`
	Width                int64    `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageResource) Reset()         { *m = ImageResource{} }
func (m *ImageResource) String() string { return proto.CompactTextString(m) }
func (*ImageResource) ProtoMessage()    {}
func (*ImageResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}
func (m *ImageResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageResource.Unmarshal(m, b)
}
func (m *ImageResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageResource.Marshal(b, m, deterministic)
}
func (m *ImageResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageResource.Merge(m, src)
}
func (m *ImageResource) XXX_Size() int {
	return xxx_messageInfo_ImageResource.Size(m)
}
func (m *ImageResource) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageResource.DiscardUnknown(m)
}

var xxx_messageInfo_ImageResource proto.InternalMessageInfo

func (m *ImageResource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageResource) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ImageResource) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ImageResource) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ImageResource) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *ImageResource) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImageResource) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ComplexInfo struct {
	ViewType             string                    `protobuf:"bytes,1,opt,name=view_type,json=viewType,proto3" json:"view_type,omitempty"`
	CardInfo             *ComplexInfo_CardInfo     `protobuf:"bytes,2,opt,name=card_info,json=cardInfo,proto3" json:"card_info,omitempty"`
	PlayList             *ComplexInfo_PlayList     `protobuf:"bytes,3,opt,name=play_list,json=playList,proto3" json:"play_list,omitempty"`
	Table                *ComplexInfo_TableInfo    `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Carousel             *ComplexInfo_CarouselInfo `protobuf:"bytes,5,opt,name=carousel,proto3" json:"carousel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ComplexInfo) Reset()         { *m = ComplexInfo{} }
func (m *ComplexInfo) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo) ProtoMessage()    {}
func (*ComplexInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}
func (m *ComplexInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo.Unmarshal(m, b)
}
func (m *ComplexInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo.Marshal(b, m, deterministic)
}
func (m *ComplexInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo.Merge(m, src)
}
func (m *ComplexInfo) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo.Size(m)
}
func (m *ComplexInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo proto.InternalMessageInfo

func (m *ComplexInfo) GetViewType() string {
	if m != nil {
		return m.ViewType
	}
	return ""
}

func (m *ComplexInfo) GetCardInfo() *ComplexInfo_CardInfo {
	if m != nil {
		return m.CardInfo
	}
	return nil
}

func (m *ComplexInfo) GetPlayList() *ComplexInfo_PlayList {
	if m != nil {
		return m.PlayList
	}
	return nil
}

func (m *ComplexInfo) GetTable() *ComplexInfo_TableInfo {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *ComplexInfo) GetCarousel() *ComplexInfo_CarouselInfo {
	if m != nil {
		return m.Carousel
	}
	return nil
}

type ComplexInfo_CardInfo struct {
	Title                string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string         `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Icon                 string         `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	LandingPage          string         `protobuf:"bytes,4,opt,name=landing_page,json=landingPage,proto3" json:"landing_page,omitempty"`
	Layout               string         `protobuf:"bytes,5,opt,name=layout,proto3" json:"layout,omitempty"`
	Tts                  *AudioResource `protobuf:"bytes,6,opt,name=tts,proto3" json:"tts,omitempty"`
	ShortAnswer          string         `protobuf:"bytes,7,opt,name=short_answer,json=shortAnswer,proto3" json:"short_answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ComplexInfo_CardInfo) Reset()         { *m = ComplexInfo_CardInfo{} }
func (m *ComplexInfo_CardInfo) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo_CardInfo) ProtoMessage()    {}
func (*ComplexInfo_CardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 0}
}
func (m *ComplexInfo_CardInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo_CardInfo.Unmarshal(m, b)
}
func (m *ComplexInfo_CardInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo_CardInfo.Marshal(b, m, deterministic)
}
func (m *ComplexInfo_CardInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo_CardInfo.Merge(m, src)
}
func (m *ComplexInfo_CardInfo) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo_CardInfo.Size(m)
}
func (m *ComplexInfo_CardInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo_CardInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo_CardInfo proto.InternalMessageInfo

func (m *ComplexInfo_CardInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ComplexInfo_CardInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ComplexInfo_CardInfo) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *ComplexInfo_CardInfo) GetLandingPage() string {
	if m != nil {
		return m.LandingPage
	}
	return ""
}

func (m *ComplexInfo_CardInfo) GetLayout() string {
	if m != nil {
		return m.Layout
	}
	return ""
}

func (m *ComplexInfo_CardInfo) GetTts() *AudioResource {
	if m != nil {
		return m.Tts
	}
	return nil
}

func (m *ComplexInfo_CardInfo) GetShortAnswer() string {
	if m != nil {
		return m.ShortAnswer
	}
	return ""
}

type ComplexInfo_PlayList struct {
	ShortAnswer          string           `protobuf:"bytes,1,opt,name=short_answer,json=shortAnswer,proto3" json:"short_answer,omitempty"`
	Tts                  *AudioResource   `protobuf:"bytes,2,opt,name=tts,proto3" json:"tts,omitempty"`
	AudioResourceGroup   []*AudioResource `protobuf:"bytes,3,rep,name=audio_resource_group,json=audioResourceGroup,proto3" json:"audio_resource_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ComplexInfo_PlayList) Reset()         { *m = ComplexInfo_PlayList{} }
func (m *ComplexInfo_PlayList) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo_PlayList) ProtoMessage()    {}
func (*ComplexInfo_PlayList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 1}
}
func (m *ComplexInfo_PlayList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo_PlayList.Unmarshal(m, b)
}
func (m *ComplexInfo_PlayList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo_PlayList.Marshal(b, m, deterministic)
}
func (m *ComplexInfo_PlayList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo_PlayList.Merge(m, src)
}
func (m *ComplexInfo_PlayList) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo_PlayList.Size(m)
}
func (m *ComplexInfo_PlayList) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo_PlayList.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo_PlayList proto.InternalMessageInfo

func (m *ComplexInfo_PlayList) GetShortAnswer() string {
	if m != nil {
		return m.ShortAnswer
	}
	return ""
}

func (m *ComplexInfo_PlayList) GetTts() *AudioResource {
	if m != nil {
		return m.Tts
	}
	return nil
}

func (m *ComplexInfo_PlayList) GetAudioResourceGroup() []*AudioResource {
	if m != nil {
		return m.AudioResourceGroup
	}
	return nil
}

type ComplexInfo_TableInfo struct {
	ShortAnswer          string                             `protobuf:"bytes,1,opt,name=short_answer,json=shortAnswer,proto3" json:"short_answer,omitempty"`
	Tts                  *AudioResource                     `protobuf:"bytes,2,opt,name=tts,proto3" json:"tts,omitempty"`
	Title                string                             `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Thead                []*ComplexInfo_TableInfo_TableCell `protobuf:"bytes,4,rep,name=thead,proto3" json:"thead,omitempty"`
	Tbody                []*ComplexInfo_TableInfo_TableCell `protobuf:"bytes,5,rep,name=tbody,proto3" json:"tbody,omitempty"`
	Tfoot                []*ComplexInfo_TableInfo_TableCell `protobuf:"bytes,6,rep,name=tfoot,proto3" json:"tfoot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ComplexInfo_TableInfo) Reset()         { *m = ComplexInfo_TableInfo{} }
func (m *ComplexInfo_TableInfo) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo_TableInfo) ProtoMessage()    {}
func (*ComplexInfo_TableInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 2}
}
func (m *ComplexInfo_TableInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo_TableInfo.Unmarshal(m, b)
}
func (m *ComplexInfo_TableInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo_TableInfo.Marshal(b, m, deterministic)
}
func (m *ComplexInfo_TableInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo_TableInfo.Merge(m, src)
}
func (m *ComplexInfo_TableInfo) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo_TableInfo.Size(m)
}
func (m *ComplexInfo_TableInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo_TableInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo_TableInfo proto.InternalMessageInfo

func (m *ComplexInfo_TableInfo) GetShortAnswer() string {
	if m != nil {
		return m.ShortAnswer
	}
	return ""
}

func (m *ComplexInfo_TableInfo) GetTts() *AudioResource {
	if m != nil {
		return m.Tts
	}
	return nil
}

func (m *ComplexInfo_TableInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ComplexInfo_TableInfo) GetThead() []*ComplexInfo_TableInfo_TableCell {
	if m != nil {
		return m.Thead
	}
	return nil
}

func (m *ComplexInfo_TableInfo) GetTbody() []*ComplexInfo_TableInfo_TableCell {
	if m != nil {
		return m.Tbody
	}
	return nil
}

func (m *ComplexInfo_TableInfo) GetTfoot() []*ComplexInfo_TableInfo_TableCell {
	if m != nil {
		return m.Tfoot
	}
	return nil
}

type ComplexInfo_TableInfo_TableCell struct {
	CellType             string         `protobuf:"bytes,1,opt,name=cell_type,json=cellType,proto3" json:"cell_type,omitempty"`
	TextData             string         `protobuf:"bytes,2,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	ImgData              *ImageResource `protobuf:"bytes,3,opt,name=img_data,json=imgData,proto3" json:"img_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ComplexInfo_TableInfo_TableCell) Reset()         { *m = ComplexInfo_TableInfo_TableCell{} }
func (m *ComplexInfo_TableInfo_TableCell) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo_TableInfo_TableCell) ProtoMessage()    {}
func (*ComplexInfo_TableInfo_TableCell) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 2, 0}
}
func (m *ComplexInfo_TableInfo_TableCell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo_TableInfo_TableCell.Unmarshal(m, b)
}
func (m *ComplexInfo_TableInfo_TableCell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo_TableInfo_TableCell.Marshal(b, m, deterministic)
}
func (m *ComplexInfo_TableInfo_TableCell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo_TableInfo_TableCell.Merge(m, src)
}
func (m *ComplexInfo_TableInfo_TableCell) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo_TableInfo_TableCell.Size(m)
}
func (m *ComplexInfo_TableInfo_TableCell) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo_TableInfo_TableCell.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo_TableInfo_TableCell proto.InternalMessageInfo

func (m *ComplexInfo_TableInfo_TableCell) GetCellType() string {
	if m != nil {
		return m.CellType
	}
	return ""
}

func (m *ComplexInfo_TableInfo_TableCell) GetTextData() string {
	if m != nil {
		return m.TextData
	}
	return ""
}

func (m *ComplexInfo_TableInfo_TableCell) GetImgData() *ImageResource {
	if m != nil {
		return m.ImgData
	}
	return nil
}

type ComplexInfo_CarouselInfo struct {
	ShortAnswer          string                            `protobuf:"bytes,1,opt,name=short_answer,json=shortAnswer,proto3" json:"short_answer,omitempty"`
	Tts                  *AudioResource                    `protobuf:"bytes,2,opt,name=tts,proto3" json:"tts,omitempty"`
	Title                string                            `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Images               []*ComplexInfo_CarouselInfo_Image `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Speed                int64                             `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ComplexInfo_CarouselInfo) Reset()         { *m = ComplexInfo_CarouselInfo{} }
func (m *ComplexInfo_CarouselInfo) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo_CarouselInfo) ProtoMessage()    {}
func (*ComplexInfo_CarouselInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 3}
}
func (m *ComplexInfo_CarouselInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo_CarouselInfo.Unmarshal(m, b)
}
func (m *ComplexInfo_CarouselInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo_CarouselInfo.Marshal(b, m, deterministic)
}
func (m *ComplexInfo_CarouselInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo_CarouselInfo.Merge(m, src)
}
func (m *ComplexInfo_CarouselInfo) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo_CarouselInfo.Size(m)
}
func (m *ComplexInfo_CarouselInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo_CarouselInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo_CarouselInfo proto.InternalMessageInfo

func (m *ComplexInfo_CarouselInfo) GetShortAnswer() string {
	if m != nil {
		return m.ShortAnswer
	}
	return ""
}

func (m *ComplexInfo_CarouselInfo) GetTts() *AudioResource {
	if m != nil {
		return m.Tts
	}
	return nil
}

func (m *ComplexInfo_CarouselInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ComplexInfo_CarouselInfo) GetImages() []*ComplexInfo_CarouselInfo_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *ComplexInfo_CarouselInfo) GetSpeed() int64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type ComplexInfo_CarouselInfo_Image struct {
	Image                *ImageResource `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	LandingPage          string         `protobuf:"bytes,2,opt,name=landing_page,json=landingPage,proto3" json:"landing_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ComplexInfo_CarouselInfo_Image) Reset()         { *m = ComplexInfo_CarouselInfo_Image{} }
func (m *ComplexInfo_CarouselInfo_Image) String() string { return proto.CompactTextString(m) }
func (*ComplexInfo_CarouselInfo_Image) ProtoMessage()    {}
func (*ComplexInfo_CarouselInfo_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8, 3, 0}
}
func (m *ComplexInfo_CarouselInfo_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexInfo_CarouselInfo_Image.Unmarshal(m, b)
}
func (m *ComplexInfo_CarouselInfo_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexInfo_CarouselInfo_Image.Marshal(b, m, deterministic)
}
func (m *ComplexInfo_CarouselInfo_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexInfo_CarouselInfo_Image.Merge(m, src)
}
func (m *ComplexInfo_CarouselInfo_Image) XXX_Size() int {
	return xxx_messageInfo_ComplexInfo_CarouselInfo_Image.Size(m)
}
func (m *ComplexInfo_CarouselInfo_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexInfo_CarouselInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexInfo_CarouselInfo_Image proto.InternalMessageInfo

func (m *ComplexInfo_CarouselInfo_Image) GetImage() *ImageResource {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *ComplexInfo_CarouselInfo_Image) GetLandingPage() string {
	if m != nil {
		return m.LandingPage
	}
	return ""
}

type ControlInfo struct {
	Category             string   `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlInfo) Reset()         { *m = ControlInfo{} }
func (m *ControlInfo) String() string { return proto.CompactTextString(m) }
func (*ControlInfo) ProtoMessage()    {}
func (*ControlInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9}
}
func (m *ControlInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlInfo.Unmarshal(m, b)
}
func (m *ControlInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlInfo.Marshal(b, m, deterministic)
}
func (m *ControlInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlInfo.Merge(m, src)
}
func (m *ControlInfo) XXX_Size() int {
	return xxx_messageInfo_ControlInfo.Size(m)
}
func (m *ControlInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ControlInfo proto.InternalMessageInfo

func (m *ControlInfo) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ControlInfo) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ControlInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("schemago.SkillInfo_SkillType", SkillInfo_SkillType_name, SkillInfo_SkillType_value)
	proto.RegisterEnum("schemago.SkillAnswer_AnswerType", SkillAnswer_AnswerType_name, SkillAnswer_AnswerType_value)
	proto.RegisterEnum("schemago.TextInfo_FullAnswer_TextAnswerType", TextInfo_FullAnswer_TextAnswerType_name, TextInfo_FullAnswer_TextAnswerType_value)
	proto.RegisterEnum("schemago.AudioResource_AudioType", AudioResource_AudioType_name, AudioResource_AudioType_value)
	proto.RegisterEnum("schemago.ComplexInfo_ViewType", ComplexInfo_ViewType_name, ComplexInfo_ViewType_value)
	proto.RegisterEnum("schemago.ComplexInfo_CardInfo_Layout", ComplexInfo_CardInfo_Layout_name, ComplexInfo_CardInfo_Layout_value)
	proto.RegisterEnum("schemago.ComplexInfo_TableInfo_TableCell_TableCellType", ComplexInfo_TableInfo_TableCell_TableCellType_name, ComplexInfo_TableInfo_TableCell_TableCellType_value)
	proto.RegisterEnum("schemago.ControlInfo_ControlCategory", ControlInfo_ControlCategory_name, ControlInfo_ControlCategory_value)
	proto.RegisterEnum("schemago.ControlInfo_AppCommand", ControlInfo_AppCommand_name, ControlInfo_AppCommand_value)
	proto.RegisterEnum("schemago.ControlInfo_PlayCommand", ControlInfo_PlayCommand_name, ControlInfo_PlayCommand_value)
	proto.RegisterEnum("schemago.ControlInfo_DeviceCommand", ControlInfo_DeviceCommand_name, ControlInfo_DeviceCommand_value)
	proto.RegisterEnum("schemago.ControlInfo_PageCommand", ControlInfo_PageCommand_name, ControlInfo_PageCommand_value)
	proto.RegisterType((*SkillInfo)(nil), "schemago.SkillInfo")
	proto.RegisterType((*SkillAnswer)(nil), "schemago.SkillAnswer")
	proto.RegisterType((*TextInfo)(nil), "schemago.TextInfo")
	proto.RegisterType((*TextInfo_FullAnswer)(nil), "schemago.TextInfo.FullAnswer")
	proto.RegisterType((*Author)(nil), "schemago.Author")
	proto.RegisterType((*Album)(nil), "schemago.Album")
	proto.RegisterType((*AudioResource)(nil), "schemago.AudioResource")
	proto.RegisterType((*AudioInfo)(nil), "schemago.AudioInfo")
	proto.RegisterType((*ImageResource)(nil), "schemago.ImageResource")
	proto.RegisterType((*ComplexInfo)(nil), "schemago.ComplexInfo")
	proto.RegisterType((*ComplexInfo_CardInfo)(nil), "schemago.ComplexInfo.CardInfo")
	proto.RegisterType((*ComplexInfo_PlayList)(nil), "schemago.ComplexInfo.PlayList")
	proto.RegisterType((*ComplexInfo_TableInfo)(nil), "schemago.ComplexInfo.TableInfo")
	proto.RegisterType((*ComplexInfo_TableInfo_TableCell)(nil), "schemago.ComplexInfo.TableInfo.TableCell")
	proto.RegisterType((*ComplexInfo_CarouselInfo)(nil), "schemago.ComplexInfo.CarouselInfo")
	proto.RegisterType((*ComplexInfo_CarouselInfo_Image)(nil), "schemago.ComplexInfo.CarouselInfo.Image")
	proto.RegisterType((*ControlInfo)(nil), "schemago.ControlInfo")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 1707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0xcf, 0x6e, 0xe4, 0x48,
	0x19, 0x5f, 0xdb, 0xfd, 0xc7, 0xfd, 0x75, 0x27, 0xa9, 0xad, 0x09, 0xac, 0xe9, 0xd5, 0xb2, 0x33,
	0x96, 0x90, 0x66, 0x11, 0xd3, 0x11, 0x59, 0x21, 0x21, 0x56, 0xda, 0x21, 0xc9, 0xec, 0xc0, 0x48,
	0x09, 0x04, 0xa7, 0xb3, 0x12, 0x5c, 0xa2, 0x8a, 0x5d, 0xe9, 0x2e, 0xc5, 0x76, 0x19, 0xbb, 0x9c,
	0x4e, 0x1f, 0xb9, 0x70, 0xe1, 0x05, 0xb8, 0x23, 0x0e, 0x48, 0x9c, 0x78, 0x0a, 0x1e, 0x00, 0x89,
	0x33, 0xe2, 0x09, 0x78, 0x01, 0x84, 0xbe, 0xaa, 0xb2, 0xbb, 0x3b, 0x99, 0x28, 0x33, 0xd2, 0x8a,
	0x5b, 0x7d, 0x7f, 0xeb, 0xfb, 0xfb, 0x2b, 0x77, 0xc3, 0xa8, 0x8a, 0xe7, 0x3c, 0x63, 0x93, 0xa2,
	0x94, 0x4a, 0x52, 0xdf, 0x50, 0x33, 0x19, 0xfe, 0xd7, 0x81, 0xc1, 0xd9, 0xb5, 0x48, 0xd3, 0x37,
	0xf9, 0x95, 0xa4, 0x14, 0x3a, 0x39, 0xcb, 0x78, 0xe0, 0x3c, 0x75, 0x9e, 0x0f, 0x22, 0x7d, 0xa6,
	0xdf, 0x01, 0xbf, 0x42, 0x85, 0x0b, 0x91, 0x04, 0xae, 0xe6, 0xf7, 0x35, 0xfd, 0x26, 0xa1, 0x9f,
	0x00, 0x18, 0x91, 0x5a, 0x16, 0x3c, 0xf0, 0xb4, 0x70, 0xa0, 0x39, 0xd3, 0x65, 0xc1, 0xd1, 0x5b,
	0xc2, 0xab, 0x38, 0xe8, 0x18, 0x6f, 0x78, 0xa6, 0xdf, 0x86, 0x1e, 0xab, 0xd5, 0x5c, 0x96, 0x41,
	0x57, 0x73, 0x2d, 0x85, 0xba, 0x22, 0x96, 0x79, 0xd0, 0x33, 0xba, 0x78, 0xc6, 0x9b, 0x8b, 0xfa,
	0xf2, 0x42, 0x89, 0x8c, 0x07, 0xfd, 0xa7, 0xce, 0x73, 0x2f, 0xea, 0x17, 0xf5, 0xe5, 0x54, 0x64,
	0x9c, 0x06, 0xd0, 0xbf, 0xe1, 0x65, 0x25, 0x64, 0x1e, 0xf8, 0x26, 0x26, 0x4b, 0x86, 0x13, 0x9b,
	0x8f, 0x8e, 0x60, 0x08, 0xfd, 0xf3, 0xfc, 0x3a, 0x97, 0x8b, 0x9c, 0x7c, 0x40, 0x01, 0x7a, 0x67,
	0xcb, 0x4a, 0xf1, 0x8c, 0x38, 0xd4, 0x87, 0xce, 0x79, 0xc5, 0x4b, 0xe2, 0x86, 0xff, 0x74, 0x61,
	0xa8, 0x0d, 0x0e, 0xf2, 0x6a, 0xc1, 0x4b, 0x3a, 0x06, 0x3f, 0x96, 0x59, 0x91, 0x72, 0x65, 0xca,
	0xe0, 0x47, 0x2d, 0x4d, 0x3f, 0x85, 0x21, 0xd3, 0x5a, 0x26, 0x61, 0x53, 0x0d, 0x30, 0x2c, 0x7d,
	0xdf, 0x1e, 0x0c, 0x14, 0xbf, 0x55, 0x17, 0x22, 0xbf, 0x92, 0xba, 0x1e, 0xc3, 0x7d, 0x3a, 0x69,
	0x6a, 0x3d, 0x99, 0xf2, 0x5b, 0x85, 0x65, 0x8e, 0x7c, 0x65, 0x4f, 0x74, 0x1f, 0x80, 0xd5, 0x89,
	0x90, 0xc6, 0xa2, 0xa3, 0x2d, 0x9e, 0xac, 0x2c, 0x0e, 0x50, 0xa6, 0x4d, 0x06, 0xac, 0x39, 0xd2,
	0x1f, 0xc3, 0xc8, 0x44, 0x74, 0x6b, 0xac, 0xba, 0xda, 0xea, 0x5b, 0x2b, 0xab, 0x23, 0x23, 0xd5,
	0x76, 0xc3, 0x78, 0x45, 0xd0, 0x3d, 0xe8, 0xc7, 0x32, 0x57, 0xa5, 0x4c, 0x75, 0x9d, 0xef, 0x18,
	0x69, 0x81, 0x36, 0x6a, 0xb4, 0xc2, 0x2f, 0x00, 0x0e, 0x56, 0xd9, 0x6d, 0x54, 0xd3, 0x87, 0x0e,
	0xe6, 0x43, 0x1c, 0x3a, 0x80, 0xae, 0x8e, 0x93, 0xb8, 0xa8, 0x61, 0x2f, 0x27, 0x5e, 0xf8, 0x1f,
	0x07, 0xfc, 0x26, 0x65, 0xfa, 0x0c, 0x46, 0xd5, 0x5c, 0x96, 0xea, 0xc2, 0x54, 0xcb, 0x4e, 0xd8,
	0x50, 0xf3, 0x6c, 0xe5, 0xbf, 0x84, 0xe1, 0x55, 0x9d, 0xa6, 0x8d, 0x86, 0xab, 0x23, 0xfc, 0xe4,
	0x7e, 0xf9, 0x26, 0xaf, 0xeb, 0xa6, 0x5b, 0x11, 0x5c, 0xb5, 0xe7, 0xf1, 0xef, 0x1c, 0x80, 0x95,
	0xe8, 0x6e, 0xb3, 0x9c, 0x7b, 0xcd, 0xc2, 0x51, 0x5c, 0x5d, 0x85, 0xa3, 0xa8, 0xa9, 0xf0, 0x27,
	0xb0, 0x8d, 0x57, 0x3d, 0x94, 0xf8, 0x08, 0xfc, 0x13, 0x56, 0x5e, 0x27, 0x48, 0x39, 0x74, 0x0b,
	0x06, 0xa7, 0x29, 0x13, 0xb9, 0xae, 0x85, 0x1b, 0xee, 0x43, 0xef, 0xa0, 0x1d, 0xe8, 0x52, 0xa6,
	0xed, 0x2a, 0xe1, 0x99, 0xee, 0x42, 0x17, 0x57, 0xaa, 0xb2, 0x17, 0x1a, 0x22, 0xfc, 0x2d, 0x74,
	0x0f, 0xd2, 0xcb, 0x3a, 0x7b, 0xeb, 0xf6, 0x35, 0x3b, 0xe4, 0xae, 0xed, 0xd0, 0xf7, 0xa1, 0x6f,
	0xb6, 0xa6, 0x0a, 0xbc, 0xa7, 0xde, 0xf3, 0xe1, 0x3e, 0x59, 0x9f, 0x18, 0x14, 0x44, 0x8d, 0x02,
	0x5e, 0x19, 0xcb, 0x1b, 0x5e, 0xda, 0x25, 0x34, 0x44, 0xf8, 0x0f, 0x17, 0xb6, 0x74, 0xcf, 0x22,
	0x5e, 0xc9, 0xba, 0x8c, 0xf9, 0x3b, 0xdf, 0x1d, 0x98, 0x11, 0xe2, 0xb9, 0xb2, 0xfb, 0xde, 0x90,
	0x08, 0x06, 0x66, 0x94, 0x75, 0xb9, 0xcd, 0x75, 0x66, 0x6a, 0x75, 0x0d, 0xd7, 0x82, 0xee, 0x3e,
	0x16, 0xf4, 0x18, 0xfc, 0xa4, 0x2e, 0x99, 0x12, 0x16, 0x10, 0xbc, 0xa8, 0xa5, 0x57, 0x09, 0xf5,
	0xd7, 0x12, 0xa2, 0xdf, 0x83, 0x2e, 0xc3, 0x1a, 0x6a, 0x34, 0x18, 0xee, 0xef, 0xac, 0xf9, 0x46,
	0x76, 0x64, 0xa4, 0x94, 0x80, 0x97, 0x89, 0x24, 0x18, 0x68, 0x53, 0x3c, 0x62, 0xd4, 0x37, 0x52,
	0xc4, 0xfc, 0x22, 0x93, 0x09, 0x0f, 0xc0, 0x44, 0xad, 0x39, 0x27, 0x32, 0xe1, 0xe1, 0x0f, 0x60,
	0x70, 0xd0, 0xa6, 0xb0, 0x31, 0x06, 0x03, 0xe8, 0x9e, 0xd4, 0x95, 0x88, 0x89, 0x43, 0xfb, 0xe0,
	0x4d, 0xa7, 0x67, 0xc4, 0x0d, 0xff, 0xe0, 0x58, 0x75, 0x3d, 0xf2, 0x9f, 0xc3, 0x50, 0x83, 0xc1,
	0xda, 0xc4, 0xbf, 0x1d, 0x0e, 0x40, 0xb5, 0xe3, 0x46, 0xdf, 0xc0, 0xae, 0xa9, 0x62, 0x69, 0x3b,
	0x73, 0x31, 0x2b, 0x65, 0x5d, 0x04, 0xae, 0xae, 0xd9, 0x47, 0x77, 0xa0, 0xa1, 0x69, 0x5f, 0x44,
	0xd9, 0x3a, 0xf9, 0x33, 0x34, 0x09, 0xff, 0xe2, 0xc0, 0xd6, 0x9b, 0x8c, 0xcd, 0xf8, 0x37, 0xd8,
	0xe4, 0x15, 0x7c, 0x77, 0x36, 0xe0, 0xdb, 0x16, 0xb6, 0xbb, 0x2a, 0xec, 0x2e, 0x74, 0x17, 0x22,
	0x51, 0x73, 0xdb, 0x40, 0x43, 0xa0, 0xfd, 0x9c, 0x8b, 0xd9, 0x5c, 0x59, 0x40, 0xb7, 0x54, 0xf8,
	0xb7, 0x11, 0x0c, 0xd7, 0x60, 0x8b, 0x7e, 0x0c, 0x83, 0x1b, 0xc1, 0x17, 0xeb, 0xab, 0xeb, 0x23,
	0x43, 0xf7, 0xe1, 0x0b, 0x18, 0xc4, 0xac, 0x4c, 0x0c, 0xfa, 0x19, 0x98, 0xf8, 0xee, 0x5b, 0xd1,
	0x6f, 0x72, 0xc4, 0xca, 0xc4, 0x20, 0x6e, 0x6c, 0x4f, 0x68, 0x5c, 0xa4, 0x6c, 0x79, 0x91, 0x8a,
	0x4a, 0x59, 0x88, 0x7e, 0xc0, 0xf8, 0x34, 0x65, 0xcb, 0x63, 0x51, 0xa9, 0xc8, 0x2f, 0xec, 0x89,
	0xfe, 0x08, 0xba, 0x8a, 0x5d, 0xa6, 0xdc, 0x22, 0xf5, 0xa7, 0x6f, 0x37, 0x9c, 0xa2, 0x8a, 0xbe,
	0xd6, 0x68, 0xd3, 0x2f, 0x01, 0xef, 0x97, 0x75, 0xc5, 0x53, 0x8b, 0xd6, 0xe1, 0x83, 0xf1, 0x6a,
	0xad, 0x36, 0x66, 0x4d, 0x8d, 0xff, 0xe8, 0x82, 0xdf, 0xa4, 0x82, 0x85, 0x55, 0x42, 0xb5, 0xc8,
	0x62, 0x88, 0xf5, 0x96, 0xb9, 0x9b, 0x2d, 0x6b, 0x5e, 0x56, 0x6f, 0xed, 0x65, 0x7d, 0x06, 0xa3,
	0x94, 0xe5, 0x89, 0xc8, 0x67, 0x17, 0x05, 0x9b, 0x35, 0xdb, 0x3a, 0xb4, 0xbc, 0x53, 0x36, 0xd3,
	0xe8, 0x98, 0xb2, 0xa5, 0xac, 0x55, 0xf3, 0x50, 0x1b, 0x8a, 0x7e, 0x06, 0x9e, 0x52, 0x95, 0x7d,
	0x3f, 0x1e, 0x9c, 0x47, 0xd4, 0xb9, 0x87, 0xf9, 0xfd, 0x7b, 0x98, 0x1f, 0xbe, 0x84, 0xde, 0xb1,
	0xf1, 0xbb, 0xb1, 0x5c, 0xb8, 0x51, 0xb2, 0x30, 0xef, 0xf4, 0x31, 0xbf, 0x52, 0xc4, 0xc5, 0x7d,
	0x8b, 0x70, 0x54, 0x88, 0x87, 0x0f, 0xf9, 0xa1, 0x54, 0x4a, 0x66, 0xa4, 0x33, 0xfe, 0x93, 0x03,
	0x7e, 0xd3, 0xa8, 0x77, 0x79, 0x64, 0x6c, 0xf8, 0xee, 0x3b, 0x84, 0xff, 0xd0, 0x2a, 0x7a, 0xef,
	0xbd, 0x8a, 0xe3, 0x7f, 0x79, 0x30, 0x68, 0xa7, 0xe2, 0x1b, 0x0e, 0xb3, 0x9d, 0x07, 0x6f, 0x7d,
	0x1e, 0x5e, 0x42, 0x57, 0xcd, 0x39, 0x4b, 0x82, 0x8e, 0x8e, 0xf6, 0xb3, 0x47, 0x26, 0xd5, 0x9c,
	0x8e, 0x78, 0x9a, 0x46, 0xc6, 0x4e, 0x3b, 0xb8, 0x94, 0xc9, 0xd2, 0xa2, 0xf5, 0x7b, 0x39, 0x40,
	0x3b, 0xed, 0xe0, 0x4a, 0x4a, 0x15, 0xf4, 0xde, 0xdf, 0x01, 0xda, 0x8d, 0xff, 0xea, 0xd8, 0xa2,
	0x21, 0x13, 0x11, 0x21, 0xe6, 0xcd, 0xa7, 0xa6, 0x45, 0x04, 0x64, 0x68, 0x44, 0xf8, 0xd8, 0x7e,
	0x77, 0x25, 0x4c, 0x31, 0x3b, 0xff, 0xfa, 0x1b, 0xeb, 0x15, 0x53, 0x8c, 0xee, 0x83, 0x2f, 0xb2,
	0x99, 0x91, 0x79, 0x77, 0x0b, 0xba, 0x01, 0x90, 0x51, 0x5f, 0x64, 0x33, 0xb4, 0x09, 0x7f, 0x08,
	0x5b, 0xed, 0xd5, 0x8f, 0x7c, 0xfb, 0x68, 0x0f, 0xc4, 0x1d, 0xff, 0xd9, 0x85, 0xd1, 0xfa, 0xfe,
	0xfe, 0x5f, 0xda, 0xfc, 0x53, 0xe8, 0x09, 0xbc, 0xbf, 0xb2, 0x7d, 0x7e, 0xfe, 0x38, 0xae, 0xd8,
	0x94, 0xad, 0x1d, 0xfa, 0xad, 0x0a, 0xce, 0x0d, 0x76, 0x7b, 0x91, 0x21, 0xc6, 0xbf, 0xb6, 0x79,
	0xd1, 0x17, 0xd0, 0xd5, 0x8a, 0xf6, 0xf9, 0x7a, 0xb0, 0x72, 0x46, 0xeb, 0x1e, 0xb0, 0xb8, 0xf7,
	0x80, 0x25, 0xfc, 0x39, 0xf8, 0x5f, 0x37, 0x48, 0x7e, 0xb7, 0xaa, 0x08, 0x72, 0xc4, 0xc1, 0x4f,
	0x2c, 0xdc, 0x69, 0x84, 0x68, 0xb3, 0xf9, 0xba, 0x17, 0xc4, 0x43, 0x41, 0x93, 0x0a, 0xe9, 0x84,
	0xbf, 0xef, 0xe3, 0xa3, 0xd1, 0x7e, 0xb6, 0xea, 0x4f, 0x77, 0xa6, 0xf8, 0x4c, 0x96, 0xcb, 0x76,
	0x42, 0x2c, 0x6d, 0xf0, 0x31, 0xcb, 0x58, 0x9e, 0xac, 0xf0, 0x51, 0x93, 0x58, 0x80, 0x1b, 0x96,
	0xd6, 0x6d, 0x61, 0x35, 0x11, 0xc6, 0xb0, 0x63, 0x5d, 0x1f, 0x35, 0x2e, 0x36, 0x82, 0xdd, 0x06,
	0x38, 0x28, 0x0a, 0xab, 0x42, 0x1c, 0xba, 0x03, 0x43, 0x0c, 0xb9, 0x61, 0xb8, 0xf4, 0x43, 0xd8,
	0x7a, 0xc5, 0x6f, 0x44, 0xcc, 0x1b, 0x96, 0xa7, 0x75, 0xd8, 0xac, 0x65, 0x74, 0xc2, 0x67, 0xd6,
	0x89, 0x09, 0xc4, 0x87, 0xce, 0x2f, 0x0b, 0x6e, 0xbf, 0x2d, 0x8e, 0x52, 0x59, 0x71, 0xe2, 0x84,
	0x7f, 0x77, 0x1b, 0xc7, 0xad, 0xd2, 0x69, 0xc9, 0x6f, 0x4c, 0xb9, 0x7e, 0x61, 0x86, 0x70, 0x04,
	0xfe, 0x6b, 0x76, 0x23, 0x4b, 0xa1, 0x38, 0x71, 0x31, 0xb2, 0xf3, 0xbc, 0xa5, 0x3d, 0xba, 0x0b,
	0x04, 0x1d, 0xe0, 0xe7, 0x4c, 0xfa, 0x8a, 0x5f, 0xb1, 0x3a, 0x55, 0xa4, 0x83, 0xe1, 0xb5, 0xdc,
	0x63, 0x29, 0x0b, 0xd2, 0xa5, 0x4f, 0x60, 0xa7, 0x65, 0x45, 0x2c, 0x4f, 0x64, 0x46, 0x7a, 0xf4,
	0x23, 0x78, 0x72, 0x87, 0xa9, 0xb5, 0xfb, 0x1b, 0x82, 0x33, 0x91, 0xcf, 0x52, 0xae, 0x05, 0xbe,
	0xfe, 0x99, 0xc5, 0xf9, 0xf5, 0x54, 0x92, 0x01, 0x66, 0xfc, 0x9a, 0x55, 0xea, 0xb5, 0x2c, 0x17,
	0xd8, 0x59, 0x40, 0x61, 0xc4, 0x17, 0x22, 0x4f, 0xc8, 0x10, 0x43, 0x58, 0x13, 0x4e, 0x25, 0x19,
	0x61, 0x26, 0x46, 0x3c, 0x95, 0x64, 0xcb, 0x28, 0xe3, 0xdb, 0x4b, 0xb6, 0x75, 0xde, 0x78, 0xda,
	0xc1, 0xd3, 0x99, 0x92, 0x05, 0x21, 0x46, 0x5e, 0xd5, 0x19, 0x27, 0x1f, 0x62, 0xc9, 0x4e, 0x59,
	0x5d, 0x71, 0x42, 0xf1, 0x78, 0x86, 0x43, 0x4c, 0x9e, 0x60, 0xcb, 0x7e, 0x55, 0xb3, 0x54, 0xa8,
	0x25, 0xd9, 0x0d, 0xff, 0xed, 0xac, 0x5a, 0xd2, 0x16, 0xf3, 0x50, 0x4a, 0x65, 0x7e, 0x1b, 0x46,
	0xfc, 0x12, 0xcf, 0xba, 0x9c, 0x67, 0xf3, 0x5a, 0xe9, 0x0f, 0x7c, 0x97, 0x12, 0x18, 0x1d, 0x96,
	0xf8, 0xf0, 0xe4, 0xbc, 0xaa, 0xce, 0x0b, 0xe2, 0x51, 0x0a, 0xdb, 0x2b, 0xce, 0x2b, 0xd4, 0xea,
	0x6c, 0x6a, 0x4d, 0x25, 0xe9, 0xa2, 0x97, 0xaf, 0x72, 0xc5, 0xcb, 0xc3, 0x94, 0x93, 0x1e, 0x06,
	0xf2, 0xd5, 0xad, 0x50, 0x48, 0xf4, 0x51, 0xf4, 0xb5, 0x4c, 0xeb, 0x8c, 0x9f, 0x63, 0xbd, 0xb6,
	0x01, 0x0c, 0xa5, 0x5d, 0x0d, 0x56, 0xd2, 0xa9, 0x24, 0x80, 0x21, 0x9e, 0xd4, 0x8a, 0x93, 0x21,
	0x86, 0x78, 0x9e, 0xeb, 0xf3, 0x08, 0xdd, 0x9d, 0x88, 0x58, 0x4f, 0xcb, 0x96, 0xfe, 0x41, 0x22,
	0x62, 0x33, 0x30, 0xdb, 0x61, 0xd9, 0x0c, 0x99, 0x49, 0x51, 0x8f, 0x92, 0x88, 0xaf, 0xc9, 0x07,
	0xf8, 0x53, 0xe5, 0x58, 0xe6, 0x33, 0x43, 0x3a, 0xe8, 0x23, 0xe2, 0x57, 0x25, 0xaf, 0xe6, 0xc4,
	0xd5, 0x95, 0x60, 0xf1, 0x35, 0xf1, 0xb4, 0xc1, 0x9c, 0xc7, 0xd7, 0xa4, 0x63, 0x06, 0xde, 0x10,
	0x5d, 0x24, 0xce, 0x52, 0x91, 0x60, 0xcc, 0x3d, 0x74, 0xa5, 0x09, 0x1d, 0x72, 0xff, 0xf0, 0xe0,
	0x37, 0x2f, 0x67, 0x42, 0x4d, 0x62, 0x99, 0xf0, 0x89, 0x64, 0x93, 0x58, 0x66, 0x7b, 0x8b, 0xdb,
	0xd9, 0x8b, 0xa2, 0x8c, 0xf7, 0x6e, 0x05, 0x93, 0x0b, 0x2e, 0x5e, 0xc8, 0x82, 0xe7, 0xac, 0x10,
	0x2d, 0x6d, 0x60, 0x64, 0xaf, 0x41, 0x93, 0xcb, 0x9e, 0xfe, 0x63, 0xe2, 0xf3, 0xff, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x68, 0x87, 0xdf, 0x71, 0xa8, 0x10, 0x00, 0x00,
}
